services:
  web:
    build: .
    ports:
      - "5678:3000"
    command: npm run start

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web