services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: npm run start

  nginx:
    image: nginx:latest
    ports:
      - "5678:5678"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web